### ISSUE TITLE
Face not rendering properly in demo

### ISSUE THREAD

**Issue by 123pyLeo** [ShenhanQian/GaussianAvatars#95]
![Image](https://github.com/user-attachments/assets/8b265597-e514-46bc-99f6-5f7aa1febb41)

I'm trying to use the trained GaussianAvatar without downloading the dataset by running:
python local_viewer.py --point_path media/306/point_cloud.ply

However, I found that the face is not rendering properly, as shown in the image. Could you please help me understand what might be causing this issue and suggest any possible solutions?

**Comment by ShenhanQian** [comment]
Hi, it seems that the 3DGS rasterizer isn't working properly. Did you use exactly the same setting as shown [here](https://github.com/ShenhanQian/GaussianAvatars/blob/main/doc/installation.md#tested-platforms) for Windows? It worked when I released the code, but I don't have a Windows machine to test it again. 

But here are two alternatives you could try:
1. Try [the other branch](https://github.com/ShenhanQian/GaussianAvatars/tree/gsplat) of the repo that uses a different 3DGS rasterizer (gsplat).
2. Work in Ubuntu via WSL (Windows Subsystem for Linux).

Before doing the above, you can quickly check if the meshes are properly loaded by selecting 'show mesh' and de-selecting 'show splatting.'

**Comment by abcliguanxi** [comment]
I also have this same problem. My env:
Windows11
PyTorch Version: 2.2.0
CUDA version : 12.1.1
Windows (VS2022):

**Comment by ShenhanQian** [comment]
Hi @abcliguanxi, have you tried the suggestions above? Does any of them work?

**Comment by abcliguanxi** [comment]
yes.i tried the method 1. but it but still have the problem.

![Image](https://github.com/user-attachments/assets/916e7e0d-5d79-408f-a68f-914a3f2bf5b0)

**Comment by abcliguanxi** [comment]
I used other Env and Device.As follows:
Pytorch Version: 2.0.1
Cuda Version: 11.7.1
Ubuntu20.04
GPU: 2080Ti
still have the problem.

**Comment by moliq1** [comment]
> I also have this same problem. My env: Windows11 PyTorch Version: 2.2.0 CUDA version : 12.1.1 Windows (VS2022):

same env same problems. did you found any solution yet?

**Comment by sylyt62** [comment]
<img width="1036" height="637" alt="Image" src="https://github.com/user-attachments/assets/8fd1a259-46b2-44a4-8769-08903754f241" />

I'm running on WSL2, and getting the same result. The mesh is visible, just the GS rendering part get messed up.

My setup:
WSL2 + python 3.11 + torch 2.7.1 + cuda 12.8

**Comment by sylyt62** [comment]
Check the two libraries: diff-gaussian-rasterization and simple-knn
Be sure to use the proper version/branch.
